### ISSUE TITLE
Item records don't seem to have mapped to holdings records correctly

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#12]
<strong>Submitted By: </strong>hsammons@stanford.edu
<strong>Description: </strong>For ckey `a3133515`, in Symphony there is one item at location GREEN/STACKS and one item at location  GREEN/BENDER. In Folio, both of these items appear under the holdings record for Green Bender Room. Jeanette hypothesized this might have occurred because in Symphony there is only one call number structure
<strong>Instance HRID: </strong>`a3133515`
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>
<strong>Browser: </strong>Firefox

**Comment by michelleif** [comment]
@ahafele can you look into this?

**Comment by ahafele** [comment]
Followed up with Harold and passed to libsys at https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/162
