### ISSUE TITLE
Item record doesn't display in drop-down menu under holdings

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#13]
<strong>Submitted By: </strong>hsammons@stanford.edu
<strong>Description: </strong>For HRID  `a3122354`, it looks like the item record is not in Folio. When I click the drop-down for the holdings record labeled Green Stacks (the only holdings record) the item doesn't appear. I also couldn't find the item when searching by barcode. The item is in Symphony (barcode 36105018458054)
<strong>Instance HRID: </strong>`a3122354`
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>
<strong>Browser: </strong>Firefox

**Comment by michelleif** [comment]
@ahafele can you check this one out too?

**Comment by ahafele** [comment]
Followed up with Harold and passed to libsys via https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/162
