### ISSUE TITLE
quickMARC grayed out

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#14]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>I found a record that is source MARC, but quickMARC is grayed out. I am also unable to view source. Did something go wrong with the migration of this record or is there something in the record blocking the ability to view it?
<strong>Instance HRID: </strong> `a13001612`
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by michelleif** [comment]
@ahafele i verified i couldn't view MARC either, could you check this out?

**Comment by ahafele** [comment]
@michelleif I couldn't find this record with the HRID provided, did it show for you?

**Comment by michelleif** [comment]
yes, originally the HRID was showing up truncated in ZenHub but I fixed it, try refreshing ZenHub, the HRID is a13001612

**Comment by michelleif** [comment]
argh github don't do that! the id is `a13001612`

**Comment by ahafele** [comment]
@jermnelson this is the ticket meant to ask about airflow logging.Seems like something went wrong with the posting of this to SRS. Maybe we can chat about it next week to see if there is a way for me to investigate issues like this.
