### ISSUE TITLE
Linked 880 field to 245

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#17]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>880	0 1	‡6 245-01//r ‡a השדה. is being displayed in Inventory as Variant title, which I would have assumed would be a 246 field. Is this the correct name for this?
<strong>Instance HRID: </strong>`a4243656`
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by michelleif** [comment]
@ahafele for you

**Comment by ahafele** [comment]
@jlkalchik because the instance title is not repeatable the linked 245 shows as a Variant title. See scenario 6 here - https://issues.folio.org/browse/MODDICORE-114.
I've seen some discussion around it on slack and there is a related ticket here - https://issues.folio.org/browse/UXPROD-1646
