### ISSUE TITLE
Holdings and item match-up issue

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#19]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>The record has two items in Symphony, one for Spec U-ARCHIVES and for SAL STACKS; They have the same call number, but are in two different call number structures, one for each library. In FOLIO there is a SPEC holding, but the effective location is SAL stacks (which matches the SAL barcode correctly) 
<strong>Instance HRID: </strong>`a1358079`
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>I need help soon.
<strong>Browser: </strong>Chrome

**Comment by michelleif** [comment]
@ahafele can you take a look at this for @jlkalchik ?

**Comment by ahafele** [comment]
Followed up with Harold and passed to libsys via https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/162
