### ISSUE TITLE
I cannot search by dewy call number TX 428.51 .G13M

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#22]
<strong>Submitted By: </strong>kells@stanford.edu
<strong>Description: </strong>I tried searching both with and without a space after the TX for the call number. I get the message Error 400: 1}. I can find the item by its title. I also tried a separate Dewey call number with the same result.
<strong>Instance HRID: </strong>`a5614177`
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by michelleif** [comment]
replying to Kelly via slack:
i was able to find the item using wildcards in call number search

<img width="1144" alt="Screen Shot 2022-08-25 at 1 07 00 PM" src="https://user-images.githubusercontent.com/23069165/186763981-ea5c7e12-740b-4c0b-9414-c0185ab86ab7.png">

but not sure yet why it doesn't work searching entire call number

**Comment by ahafele** [comment]
If there are incorrect whitespaces it won't find it. Could that be the issue?

**Comment by michelleif** [comment]
if you search by Item / Effective call number (item), normalized, then you can find it searching entire call number:
<img width="1257" alt="Screen Shot 2022-09-09 at 11 51 35 AM" src="https://user-images.githubusercontent.com/23069165/189423311-45ae0b61-2854-478b-a0d6-4160f22f54b9.png">

I tried several searches on Instance / Call number, and the 400 error seems to appear when there's a space followed by a period in the search string. I found a FOLIO JIRA for this and appears to be fixed in Morning Glory: https://issues.folio.org/browse/UIIN-2078

@ahafele if you agree that is what's happening we can move to "check in future" column and i can respond to kelly

**Comment by jlkalchik** [comment]
There is no call number in the item record. There is only the effective call number and the shelving number. I checked another Dewey number (item: 36105233355762) and an LC number (item: 36105124077657) and the item call number is not being populated. Should we expect the call number to end up in the item record during migration?

**Comment by ahafele** [comment]
@jlkalchik We are putting the call numbers at the holding level at the moment so it makes sense that you wouldn't be seeing them in the item records - they'll inherit from the holdings.  
@michelleif I'll move this to check in future.
