### ISSUE TITLE
Can't automatically charge a processing fee for declared lost items due to service point fee/fine owner issue

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss-deprecated/folio-support#24]
Testing how to automatically add a processing fee for user replaced items. The Lost item fee policy was set up to use a replacement fee. In User app, when using Declared Lost command from a loan the attached error appears. Prevents automatically adding the fee. Everything else works as expected (item checked in, marked 'declared lost'.)

However, all service points (except Online) have an associated Fee/Fine owner.

Error happens whether the borrower/staff are using the same service point or not (Lane item & Lane staff; Art item & Green staff)

This may also have to do with the service point assigned during data import mentioned in sul-dlss/FOLIO-Project-Stanford#378 

![replacement_fee_error](https://user-images.githubusercontent.com/60452238/186968676-3664eca6-3b89-40ac-b31e-d2c2820b7294.jpg)

**Comment by shelleydoljack** [comment]
Hmm. it worked for me logged in as superuser, with circ desk 2 as my service point.
![Screen Shot 2022-08-26 at 1 11 51 PM](https://user-images.githubusercontent.com/6343464/186975372-67601897-eac6-43bd-98db-5e40aaebe9d4.png)
Although I'm not sure I did the thing you were trying to do. Was there anything in FOLIO slack community about this?

**Comment by michelleif** [comment]
i can reproduce but on some items i can do "Declare lost" successfully with no error. @Laszlo-J what is an example barcode of an item that fails?

**Comment by Laszlo-J** [comment]
The one I tested is now declared lost, so I doubt it can be reused.

I still have one checked out you can test: 36105213947943

It's from Science and has a $200 lost item fee policy w/replacement fee set.

**Comment by michelleif** [comment]
scenario is user loses item and brings their own replacement?

i want to make sure i'm checking the right thing, so is step 1 to Declare lost on this screen?
<img width="1250" alt="Screen Shot 2022-08-26 at 4 05 34 PM" src="https://user-images.githubusercontent.com/23069165/187001346-9e2da2f8-f79f-4dd0-8861-b03b3e2fbbeb.png">

and then how do i indicate that user provides replacement copy?

**Comment by Laszlo-J** [comment]
Yes. That should apply the processing fee to the user, check in item, and mark declared lost in inventory. The Declare lost window requires a free-text description where you add "user replaced", etc.

**Comment by michelleif** [comment]
hmmm, puzzling. i got the error as well. how about let's ask Tara, we can pay for more consulting time.

(p.s. the `$200 lost fee policy` has setting `Set cost of 500.00` which might be a typo)

**Comment by michelleif** [comment]
let's put this on hold since you are proposing eliminating the processing fee anyway

**Comment by Laszlo-J** [comment]
Actually this is a different fee :( It's charged when a user replaces a book with another copy. We charge it to "make the item shelf ready" (catalog, bind, etc.) So we still need to make this work.

**Comment by michelleif** [comment]
got it. i will suggest in the "fine free" proposal that you clarify that some processing fees will remain
