### ISSUE TITLE
Printing of records from FOLIO

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#25]
<strong>Submitted By: </strong>hsammons@stanford.edu
<strong>Description: </strong>My staff and I are wondering if there is a way to print FOLIO records, other than by printing the entire browser page.  So far we haven't found a way to do so. It would be best if we could print individual instance, holdings, or item records in a simple format.
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Firefox

**Comment by michelleif** [comment]
[info from FOLIO Community Slack](https://folio-project.slack.com/archives/C1EPYQKCL/p1660676894734749). no solution, but others in community are interested.

**Comment by ahafele** [comment]
Printing is available in-app in Orders. 
You can print a MARC record from quickMARC fairly effectively from folio snapshot (Nolana, Morning Glory?)
Inventory printing not yet available. Tickets (both in draft form): https://issues.folio.org/browse/UXPROD-2974 and https://issues.folio.org/browse/UXPROD-3099.
Recording on requirements list and watching tickets.
