### ISSUE TITLE
Data Import and Single Record - "value already exists in table instance"

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-support#27]
Reports from Vitus and Jeanette: 

Jeanette
When trying to use Data import to add records just now it is discarding the instances because the value already exists in the table instance. Did it get reset? For example it tried to use in00000000256 which was created by me using Data import on the 14th.
The failed instances of job 92 are in order in00000000256, in00000000258, in00000000259, ... in00000000271.

Vitus
 the same issue occurred when I tried to import an OCLC record using the Inventory app's singe record import function yesterday. SRS MARC was created but the Instance was discarded because of this: "value already exists in table instance: in00000000207" Job id is 95

------------

I think this is what we are seeing - https://issues.folio.org/browse/MODDICORE-215. Looks like it is not something they will fix because no use cases were identified for changing the counter post-migration.

**Comment by michelleif** [comment]
may be related to sul-dlss/FOLIO-Project-Stanford#352?

**Comment by ahafele** [comment]
Maybe except in both of the above there was a distinct error message of "value already exists in table instance:..."

**Comment by ahafele** [comment]
Also true (but a silent error) for adding instances manually. 

Jeremy reset counter to 1000 and all is working again. We'll need to keep this in mind as we move forward. Moving to "check later"
