### ISSUE TITLE
Subject headings

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#38]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>It seems like subjects with $x are getting a -- in the instance record while $z and $v are not. Also in00000000220 has more 65X fields than are what are displaying in the instance record and none of the 655 fields have Genre: in front of them. 
<strong>Instance HRID: </strong>`a10163271 & a3967309 & in00000000220 `
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>I need help soon.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
@jlkalchik I'm not finding anything that tells me the limit on number of subjects allowed in an instance record, so I'll have to look at that further. Same with -- issue. 
Re: Genre: in front of the 655 - why are you expecting that to be there?

**Comment by jlkalchik** [comment]
HRID a11899204 has 655 | 7 | ‡a Maps ‡2 fast ‡0 (OCoLC)fst01423704 and displays in the instance as Genre: Maps. in00000000220 655 | 7 | ‡a Cookbooks. ‡2 fast ‡0 (OCoLC)fst01752725 but displays in the instance only as Cookbooks.

**Comment by shelleydoljack** [comment]
To me, this means that there is something not lining up with how MARC data from migrated records is mapping to however in00000000220 was created.

**Comment by ahafele** [comment]
@jlkalchik could you verify if this is still and issue in Nolana? If not, this ticket can be closed. Thanks!

**Comment by michelleif** [comment]
Jeanette says it's no longer an issue.
