### ISSUE TITLE
Cannot save Data Import records in quickMARC

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#39]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>I am able to open and make changes to the MARC record, including delete fields, but when i try to Save and Close I get the error "Record not saved: Communication problem with server. Please try again." I noticed this when intentionally creating errors in Data Import records today to see what would load and not load and then trying to see if I could then fix any errors that loaded. I went back and then checked recent previously loaded records, including one loaded by Vitus, and receive the same error with trying to save any of them. I have been able to successfully save changes to system loaded records. I just imported a single record in00000011641 and was not able to save an update, but was able to save an update to a single record in00000000224 that I previously imported. After finding this I went further back and checked saving a Data Import record in00000000243 and that worked just fine.
<strong>Instance HRID: </strong>`in00000011295 (bad) & in00000000243 (good) & in00000011641 (bad) & in00000000224 (good) `
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>I can't work until this is fixed.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
Cannot reproduce in Nolana
