### ISSUE TITLE
SUL Electronic holdings

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#51]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>All the coordinate libraries have SUL electronic holdings for their records with electronic resources. Should they have their own Electronic holdings? Law has electronic holdings when their items are internet, ex: a520892, but that is also confusing in that there is a SUL Electronic holding and a Law electronic holding on the record.
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>
<strong>Urgency: </strong>
<strong>Browser: </strong>

**Comment by ahafele** [comment]
Thanks for reporting @jlkalchik! This will be resolved once we complete the work here https://github.com/sul-dlss/libsys-airflow/pull/160.

**Comment by ahafele** [comment]
@jlkalchik this is done now.
