### ISSUE TITLE
All search

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#52]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>According to https://docs.folio.org/docs/metadata/inventory/ "All. Searches across all fields in all record types. May impact performance." However if I take information from a918607 and try to search Le Cerf de la Vieville, Philippe, 1677-1748 It does not find the record. Is this some delay in Indexing?
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>
<strong>Urgency: </strong>
<strong>Browser: </strong>

**Comment by michelleif** [comment]
I'm not finding any results at all when doing various searches on the "All" index, including just *.
@jermnelson is there a separate process running to index the recently loaded records?
The search on the `Keyword` does work.

**Comment by ahafele** [comment]
Not currently turned on. Josh will look into it - https://github.com/sul-dlss/folio-k8s/issues/71

**Comment by ahafele** [comment]
This is resolved and search now works. @jlkalchik
