### ISSUE TITLE
Green Federal Docs holdings 

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#54]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>The first holdings for Green Federal Docs does not have a call number in some serial records. Ex: a12798738 & a414038 
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by dlrueda** [comment]
For a414038, the holdings for the item was not created.  The holdings on the FOLIO record is the MHLD.  The item was added to this MHLD holdings.

**Comment by ahafele** [comment]
@jlkalchik I'm not sure what is happening with a414038. We'll have to look at the source data tsv. 
a12798738 does not have a call number for the holdings that is derived from MARC. This is expected behavior for MARC holdings in their unmerged state.

**Comment by ahafele** [comment]
Ah, @dlrueda's answer explains a414038

**Comment by dlrueda** [comment]
And I think we fixed the problem that caused this to happen in record 414038 in later runs.  So next load, this should be ok.
