### ISSUE TITLE
Holdings for records with 956

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#55]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>Records with a 956 are being loaded without any holdings. Should they have a SUL electronic holding?
<strong>Instance HRID: </strong>`a12900643`
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
Thanks @jlkalchik , they are being loaded this way and should have SUL electronic holdings. We have a ticket in to get this part done next round of loading.
