### ISSUE TITLE
On-order electronic records are being migrated with an item

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#58]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>Looking at Effective location for loads the last 2 days I was surprised to see SUL Electronic on the list. From what I can tell all the records are for On order electronic resources. 
<strong>Instance HRID: </strong>`ex: a14361052 `
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>I need help soon.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
Thanks Jeanette. @dlrueda I think this is because we rely on the presence of the 856 to determine if it should be handled as an e-resource. cc @jermnelson

**Comment by ahafele** [comment]
We will no longer be creating on-order items so this should be resolved in next load.
