### ISSUE TITLE
Item cat2 codes

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#59]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>The item cat codes are not in records. ex: ai6853207_2_1 should have DIGI-SCAN somewhere (maybe a statistical code?). 
<strong>Instance HRID: </strong>`a6853207`
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>I need help soon.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
Migrating to stat codes. Should be complete in next load.
