### ISSUE TITLE
Index title trailing /

### ISSUE THREAD

**Issue by michelleif** [sul-dlss-deprecated/folio-support#75]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>Harold noticed that records he copy cataloged have the / before the $c in the index title because the mapping includes all of 245$anpb, but our migrated records do not. ex: in00000000022 v. a4024899. This might not be an issue, just a difference in migrated versus FOLIO copy cataloged records.
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>
<strong>Urgency: </strong>
<strong>Browser: </strong>

**Comment by ahafele** [comment]
I believe this was resolved by Jeremy's finding re: migration tools.
